---
apiVersion: v1
kind: Namespace
metadata:
  name: hellonode
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hellonode
  namespace: hellonode
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: hellonode.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hellonode
            port:
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode
  namespace: hellonode
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hellonode
  template:
    metadata:
      labels:
        name: hellonode
    spec:
      containers:
      - name: hellonode
        image: qiuguobin/hellonode
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hellonode
  namespace: hellonode
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: hellonode
