- hosts: nodejs
  gather_facts: yes
  environment:
    PATH: "/home/guobin/.nvm/versions/node/v21.6.2/bin:{{ ansible_env.PATH }}" #非交互式shell缺少node路径
  tasks:
    - name: Copy dir to remote
      synchronize:
        src: "{{ build_dir }}"
        dest: '.'
      when: build_dir is defined  
    - name: Copy artifact to remote
      copy:
        src: "{{ artifact }}"
        dest: './hellonode'
        mode: '0755'
      when: artifact is defined
    - name: Restart PM2
      shell: pm2 restart ./hellonode/app.js -i max
      register: result
      ignore_errors: true
    - name: Start PM2
      shell: pm2 start ./hellonode/app.js -i max
      when: result is failed #is failed是ansible的固定写法检查一个任务是否失败
