- hosts: nodejs
  gather_facts: no
  tasks:
    - name: Copy hellonode to remote 
      copy:
        src: "{{ artifact }}"
        dest: "./hellonode.tgz"
        mode: '0755'
    - name: Unarchive artifact
      shell: tar -xzvf ./hellonode.tgz
    - name: Restart PM2
      shell: pm2 restart ./hellonopde/app.js -i max
