- hosts: nodejs
  gather_facts: no
  tasks:
    - name: Copy hellonode to remote 
      copy:
        src: "{{ artifact }}"
        dest: "hellonode.tgz" # 相对于/home/guobin/
        mode: '0755'
    - name: Unarchive artifact
      shell: tar -xzvf hellonode.tgz && mv package hellonode && rm hellonode
    - name: Restart PM2
      shell: pm2 restart hellonode/app.js -i max
      register: result
      ignore_errors: true
    - name: Start PM2
      shell: pm2 start hellonode/app.js -i max
      when: result is failed #is failed是ansible的固定写法检查一个任务是否失败
